### ISSUE TITLE
`.pnpm-sync.json` should be versioned.

### ISSUE THREAD

**Issue by iclanton** [tiktok/pnpm-sync#22]
The `.pnpm-sync.json` file should contain a `version` field so it can be invalidated and regenerated if its schema changes between versions of the `pnpm-sync-lib` packages, or if an issue is identified and fixed.

I'm seeing an issue on my current local clone of https://github.com/microsoft/rushstack, where the `build-tests-subspace/typescript-v4-test/node_modules/@rushstack/heft` folder is linked to the wrong location (see screenshot below) because the `sourceFolder` property was generated with the wrong value.

The `.pnpm-sync.json` file should have been regenerated after the bug creating the incorrect path was fixed, and that would have been easily identified if it contained a version field.

`apps/heft/node_modules/.pnpm-sync.json`:
```JSON
{
  "postbuildInjectedCopy": {
    "sourceFolder": "../..",
    "targetFolders": [
      {
        "folderPath": "../../../../common/temp/node_modules/.pnpm/file+..+..+apps+heft/node_modules/@rushstack/heft"
      },
      {
        "folderPath": "../../../common/temp/build-tests-subspace/node_modules/.pnpm/file+..+..+..+apps+heft_@types+node@18.17.15/node_modules/@rushstack/heft"
      }
    ]
  }
}
```

`build-tests-subspace/typescript-v4-test/node_modules/@rushstack/heft` structure:
![image](https://github.com/tiktok/pnpm-sync/assets/5010588/26ac3281-a9d3-4a30-8bdf-0f83102c0ea2)

**Comment by octogonz** [comment]
A bug was fixed with the `sourceFolder` relativity in `pnpm-sync` version 0.2.0, based on [PR #20](https://github.com/tiktok/pnpm-sync/pull/20/files#diff-bf4ec096389b97e9b5b598c540dd69db1a074f1db2eb12a3d9d11de25de14ae5):

![image](https://github.com/tiktok/pnpm-sync/assets/4673363/edfceea7-173c-45a7-9ca9-0efed75cc156)

A version field would enable `pnpm-sync` to detect a `.pnpm-sync.json`  file written by an incompatible release and ensure the file gets regenerated.
